config/routes.rb
BarcampGarden::Application.routes.draw do

  match '/events/featured_schedule' => 'events#featured_schedule', 
	  :via => [:get],
	  :as => :featured_schedule

  match '/events/:id/schedule' => 'events#schedule', 
	  :via => [:get],
	  :as => :event_schedule

  match '/events/featured_missing' => 'events#featured_missing', 
	  :via => [:get],
	  :as => :featured_missing

  match '/events/:event_id/remote_media_updates(.:format)' => 'remote_media#updates',
	  :via => [:get],
	  :as => :event_remote_media_updates

  match '/mediastream' => 'events#featured_remote_media',
	  :via => [:get],
	  :as => :featured_media

  match '/schedule' => 'events#featured_schedule',
	  :via => [:get],
	  :as => :featured_schedule

  match '/attendees' => 'events#featured_attendees',
	  :via => [:get],
	  :as => :featured_attendees

  resources :events do
	  resources :event_attendees, :path => :attendees, :as => :attendees, :controller => :event_attendees do
		  collection do
			  match '/register' => 'event_attendees#register'
			  match '/unregister' => 'event_attendees#unregister'
		  end
	  end
	  resources :rooms
	  resources :slots
	  resources :workshops do 
		  resources :workshop_attendees, :path => :attendees, :as => :attendees, :controller => :workshop_attendees do
			  collection do
				  match '/register' => 'workshop_attendees#register'
				  match '/unregister' => 'workshop_attendees#unregister'
			  end
		  end

		  match '/sync' => 'workshops#sync',
			  :via => [:get],
			  :as => :sync
	  end
	  resources :remote_media
	  resources :sponsors
  end

  resources :users
  resources :authentications

  devise_for :users, :path => 'access'

  match '/auth/:provider/callback' => 'authentications#create'  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'events#featured'

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  attr_accessible :description, :slug, :title, :room_id, :slot_id

  belongs_to :event
  belongs_to :room
  belongs_to :slot

  has_many :attendees, :dependent => :destroy, :class_name => 'WorkshopAttendee'

  validates :slug, :format => { :with => /^[a-z0-9]{5}[a-z0-9]*$/ }
  validates_uniqueness_of :slug, :scope => [:event_id]
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
	before_filter :authenticate_user!, :except => [
		:index, :show
	]
	layout 'events'

	# GET /events/:id/workshops
	def index
		@event = Event.find(params[:event_id])
		@workshops = @event.workshops
	end


	# GET /events/:event_id/workshops/:id
	def show
		@event = Event.find(params[:event_id])
		@workshop = @event.workshops.find(params[:id])
	end


	# GET /events/:event_id/workshops/new
	def new
		@event = Event.find(params[:event_id])
		@workshop = @event.workshops.new
		@workshop.room_id = params[:room_id]
		@workshop.slot_id = params[:slot_id]
	end


	# GET /events/:event_id/workshops/1/edit
	def edit
		@event = Event.find(params[:event_id])
		@workshop = @event.workshops.find(params[:id])
	end


	# POST /events/:event_id/workshops
	def create
		require 'pp'
		pp params
		@event = Event.find(params[:event_id])
		@workshop = @event.workshops.new(params[:workshop])
 
		# prefill pad on-the-fly
		description = "## #{@workshop.title}\n\n" +
			"Hashtag : ##{@workshop.slug}\n\n"

		@workshop.description = description

		if @workshop.save
			# FIXME: create etherpad text with workshop description
			redirect_to event_schedule_url(@event), 
				notice: 'Workshop was successfully created.'

			# Connect to your Etherpad Lite instance
			ether = EtherpadLite.connect(ETHERPAD_URL, ETHERPAD_APIKEY)

			# Get a Pad (or create one if it doesn't exist)
			pad = ether.pad(view_context.event_workshop_pad_name(@event,@workshop))
			pad.text = @workshop.description
		else
			render action: "new"
		end
	end


	# PUT /events/:event_id/workshops/1
	def update
		@event = Event.find(params[:event_id])
		@workshop = @event.workshops.find(params[:id])

		if @workshop.update_attributes(params[:workshop])
			redirect_to event_schedule_url(@event), 
				notice: 'Room was successfully updated.'
		else
			render action: "edit"
		end
	end


	# DELETE /events/:event_id/workshops/:id
	def destroy
		@event = Event.find(params[:event_id])
		@workshop = @event.workshops.find(params[:id])
		@workshop.destroy

		redirect_to event_schedule_url(@event)
	end

	def sync
		@event = Event.find(params[:event_id])
		@workshop = @event.workshops.find(params[:workshop_id])

		# Connect to your Etherpad Lite instance
		ether = EtherpadLite.connect(ETHERPAD_URL, ETHERPAD_APIKEY)

		# Get a Pad (or create one if it doesn't exist)
		pad = ether.pad(view_context.event_workshop_pad_name(@event,@workshop))

		#description = ReverseMarkdown.parse pad.html
		#puts description
		description = pad.text

		@workshop.description = description
		@workshop.save

		redirect_to event_workshop_url(@event,@workshop)
	end
	private

end

app/helpers/workshops_helper.rb
module WorkshopsHelper
	def event_workshop_pad_name event, workshop
		"#{event.slug}_#{workshop.slug}"
	end

	def event_workshop_pad_url event, workshop
		username = if current_user then
					   current_user.email
				   else 'anonymous'
				   end
		File.join(ETHERPAD_URL,'p',
				  event_workshop_pad_name(event,workshop) + 
				 "?showControls=false&useMonospaceFont=true&userName=#{username}")
	end
end

app/views/workshops/_form.html.haml
= form_for([@event,@workshop], :html => {:class => "form-horizontal"}) do |f|
	- if @workshop.errors.any?
		#error_explanation
			%h2= "#{pluralize(@workshop.errors.count, "error")} prohibited this workshop from being saved:"
			%ul
				- @workshop.errors.full_messages.each do |msg|
					%li= msg

	.control-group
		= f.label :title, "Title", :class=>"control-label"
		.controls
			= f.text_field :title, :class=>"input-xxlarge"

	.control-group
		= f.label :slug, "Slug", :class=>"control-label"
		.controls
			= f.text_field :slug, :class=>"input-xxlarge"

			= f.hidden_field :room_id, :value => @workshop.room_id
			= f.hidden_field :slot_id, :value => @workshop.slot_id

	.control-group
		.controls
			= f.submit 'Save', :class => "btn btn-primary" 
			= link_to 'Cancel', event_schedule_path(@event), :class => "btn"

app/views/workshops/edit.html.haml
%h1 Editing workshop

.location
	In : #{@workshop.room.name}

.datetime
	From : #{@workshop.slot.dtstart.to_formatted_s(:short)}
	&dash;
	To : #{@workshop.slot.dtstart.to_formatted_s(:short)}

= render 'form'

app/views/workshops/index.html.haml
%h1= @event.title
%h2 Listing workshops

%table
  %tr
    %th Title
    %th Description
    %th Slug
    %th
    %th
    %th

  - @workshops.each do |workshop|
    %tr
      %td= workshop.title
      %td= workshop.description
      %td= workshop.slug
      %td= link_to 'Show', workshop
      %td= link_to 'Edit', edit_event_workshop_path(@event,workshop)
      %td= link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New workshop', new_event_workshop_path

app/views/workshops/new.html.haml
%h1= @event.title
%h2 New workshop

.location
	In : #{@workshop.room.name}

.datetime
	From : #{@workshop.slot.dtstart.to_formatted_s(:short)}
	&dash;
	To : #{@workshop.slot.dtstart.to_formatted_s(:short)}


= render 'form'

app/views/workshops/show.html.haml
- content_for :title do
	= "%s : %s" % [@event.title, @workshop.title]

- if current_user && current_user.admin?
	.btn_group.pull-right


%h1= yield :title

.socialmedia.pull-right
	%span.label.label-info
		%i.icon-tag
		= @event.slug
	&nbsp;
	%span.label.label-info
		%i.icon-tag
		= @workshop.slug

.datetime
	%span.dtstart
	From :
	= @workshop.slot.dtstart.to_formatted_s(:short)
	&dash;
	%span.dtend
	To :
	= @workshop.slot.dtend.to_formatted_s(:short)
	&dash;
	%span.where
	In : 
	= @workshop.room.name

// = @workshop.description

/ %iframe{:width=>"100%", :height=>"600", :frameborder=>"no",
/ 	:src=>event_workshop_pad_url(@event,@workshop)}

.attendee-list.row
	- @workshop.attendees.each do |attendee|
		= render :partial => 'workshop_attendees/card', :locals => { :attendee => attendee }

%p= raw BlueCloth.new(@workshop.description).to_html


- if current_user && current_user.admin? then
	.btn-group.pull-right
		= link_to event_workshop_sync_path(@event,@workshop), :class=> 'btn' do
			%i.icon-refresh
			Sync etherpad
		= link_to edit_event_workshop_path(@event,@workshop), :class => 'btn' do
			%i.icon-edit
			Edit event
		= link_to new_event_workshop_attendee_path(@event,@workshop), :class => 'btn' do
			%i.icon-user
			Add attendee

= link_to event_workshop_pad_url(@event,@workshop), 
	:target=>'_blank', :class => 'btn btn-primary' do
	%i.icon-edit
	Edit report