config/routes.rb
BarcampGarden::Application.routes.draw do

  match '/events/featured_schedule' => 'events#featured_schedule', 
	  :via => [:get],
	  :as => :featured_schedule

  match '/events/:id/schedule' => 'events#schedule', 
	  :via => [:get],
	  :as => :event_schedule

  match '/events/featured_missing' => 'events#featured_missing', 
	  :via => [:get],
	  :as => :featured_missing

  match '/events/:event_id/remote_media_updates(.:format)' => 'remote_media#updates',
	  :via => [:get],
	  :as => :event_remote_media_updates

  match '/mediastream' => 'events#featured_remote_media',
	  :via => [:get],
	  :as => :featured_media

  match '/schedule' => 'events#featured_schedule',
	  :via => [:get],
	  :as => :featured_schedule

  match '/attendees' => 'events#featured_attendees',
	  :via => [:get],
	  :as => :featured_attendees

  resources :events do
	  resources :event_attendees, :path => :attendees, :as => :attendees, :controller => :event_attendees do
		  collection do
			  match '/register' => 'event_attendees#register'
			  match '/unregister' => 'event_attendees#unregister'
		  end
	  end
	  resources :rooms
	  resources :slots
	  resources :workshops do 
		  resources :workshop_attendees, :path => :attendees, :as => :attendees, :controller => :workshop_attendees do
			  collection do
				  match '/register' => 'workshop_attendees#register'
				  match '/unregister' => 'workshop_attendees#unregister'
			  end
		  end

		  match '/sync' => 'workshops#sync',
			  :via => [:get],
			  :as => :sync
	  end
	  resources :remote_media
	  resources :sponsors
  end

  resources :users
  resources :authentications

  devise_for :users, :path => 'access'

  match '/auth/:provider/callback' => 'authentications#create'  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'events#featured'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :dtend, :dtstart, :description, :slug, :title

  has_many :remote_media, :dependent => :destroy
  has_many :rooms, :dependent => :destroy
  has_many :slots, :dependent => :destroy
  has_many :sponsors, :dependent => :destroy
  has_many :workshops, :dependent => :destroy

  has_many :attendees, :dependent => :destroy, :class_name => 'EventAttendee'

  validates :slug, :format => { :with => /^[a-z0-9]+$/ },
	  :length => { :minimum => 6 }
  validates :title, :length => { :minimum => 6 }
  # FIXME: validate dtend > dtstart
  #
  #
  def current?
	  now = Time.now.utc
	  return (self.dtstart <= now && now <= self.dtend )
  end

  def upcoming?
	  now = Time.now.utc
	  return (now < self.dtstart)
  end

  def past?
	  now = Time.now.utc
	  return (self.dtend < now)
  end

  def validate
	  errors.add(:start_date, 'must be earlier than end date') if
	  self.dtstart < self.dtend
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :authenticate_user!, :except => [
		:index, 
		:show, 
		:schedule,
		:featured, 
		:featured_missing, 
		:featured_remote_media, 
		:featured_schedule,
		:featured_attendees
	]
	layout 'events'

	# GET /events
	# GET /events.json
	def index
		@events = Event.find(:all, :order => :dtstart)
	end


	# GET /events/1
	# GET /events/1.json
	def show
		@event = Event.find(params[:id])
	end


	def featured_missing
	end


	def featured
		@event = Event.first
		if @event.nil? then
			redirect_to :action => "featured_missing"
			return
		end

		redirect_to :action => "show", :id => @event.id
	end


	def featured_remote_media
		@event = Event.first
		if @event.nil? then
			redirect_to :action => "featured_missing"
			return
		end

		redirect_to event_remote_media_url(:event_id => @event.id)
	end

	def featured_schedule
		@event = Event.first
		if @event.nil? then
			redirect_to :action => "featured_missing"
			return
		end

		redirect_to :action => "schedule", :id => @event.id
	end

	def featured_attendees
		@event = Event.first
		if @event.nil? then
			redirect_to :action => "featured_missing"
			return
		end

		redirect_to :controller => "event_attendees", :action => "index", :event_id => @event.id
	end

	# GET /events/:id/schedule
	def schedule
		@event = Event.find(params[:id])

		@rooms = @event.rooms
		@slots = @event.slots
		@workshops = @event.workshops
	end


	# GET /events/new
	# GET /events/new.json
	def new
		@event = Event.new
	end

	# GET /events/1/edit
	def edit
		@event = Event.find(params[:id])
	end

	# POST /events
	# POST /events.json
	def create
		@event = Event.new(params[:event])

		if @event.save
			redirect_to @event, notice: 'Event was successfully created.'
		else
			render action: "new"
		end
	end

	# PUT /events/1
	# PUT /events/1.json
	def update
		@event = Event.find(params[:id])

		if @event.update_attributes(params[:event])
			redirect_to @event, notice: 'Event was successfully updated.'
		else
			render action: "edit"
		end
	end

	# DELETE /events/1
	# DELETE /events/1.json
	def destroy
		@event = Event.find(params[:id])
		@event.destroy

		redirect_to events_url
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/schedule/_table.html.haml
%h3= day.to_formatted_s(:long)

%table.workshop-table
	/ BUILD HEADER FIRST
	%tr
		%th.desc Slots \ Rooms
		- @rooms.each do |room|
			%th 
				= room.name
				- if current_user && current_user.admin? then
					.btn-group
						= link_to "", edit_event_room_path(@event,room),
							:class => 'btn btn-mini icon-edit'
						= link_to "", event_room_path(@event,room), 
							:method => :delete, 
							:confirm=>'Are you sure?',
							:class => 'btn btn-mini icon-remove'
		- if current_user && current_user.admin? then
			%td
				= link_to new_event_room_path(@event, :day => day), :class => 'btn' do
					%i.icon-plus
					Add room

	/ BUILD WORKSHOP GRID
	- @slots.each do |slot|
		- next if slot.dtstart.to_date != day
		%tr
			%th
				- if current_user && current_user.admin? then
					.btn-group
						= link_to "", edit_event_slot_path(@event,slot),
							:class => 'btn btn-mini icon-edit'
						= link_to "", event_slot_path(@event,slot),
							:method => :delete,
							:confirm=>'Delete workshop Are you sure?',
							:class => 'btn btn-mini icon-remove'
				= slot.dtstart.to_time.to_formatted_s(:time)
				%br/
				= slot.dtend.to_time.to_formatted_s(:time)

			- @rooms.each do |room|
				%td 
					= render :partial => 'events/schedule/workshop', :locals => { :slot => slot, :room => room }

	/ BUILD FOOTER
	- if current_user && current_user.admin? then
		%tr
			%td
				= link_to new_event_slot_path(@event, :day => day), :class => 'btn' do
					%i.icon-plus
					Add slot

app/views/events/schedule/_workshop.html.haml
- workshop = room.workshops.where(:slot_id => slot.id,:room_id=>room.id).first
- if workshop.nil?
	- if current_user && current_user.admin? then
		= link_to "Create workshop", 
			new_event_workshop_path(@event,:room_id=>room.id,:slot_id=>slot.id),
			:class => 'btn btn-primary'
	- else
		/ no workshop
		\-
- else
	- if current_user && current_user.admin? then
		.btn-group
			= link_to "", edit_event_workshop_path(@event,workshop),
				:class => 'btn btn-mini icon-edit'
			= link_to "", event_workshop_path(@event,workshop),
				:method => :delete,
				:confirm=>'Are you sure?',
				:class => 'btn btn-mini icon-remove'

	= link_to event_workshop_path(@event,workshop) do
		//:target => "_blank"
		%b= workshop.title 
		.div
			.icon-tag
			= workshop.slug