config/routes.rb
BarcampGarden::Application.routes.draw do

  match '/events/featured_schedule' => 'events#featured_schedule', 
	  :via => [:get],
	  :as => :featured_schedule

  match '/events/:id/schedule' => 'events#schedule', 
	  :via => [:get],
	  :as => :event_schedule

  match '/events/featured_missing' => 'events#featured_missing', 
	  :via => [:get],
	  :as => :featured_missing

  match '/events/:event_id/remote_media_updates(.:format)' => 'remote_media#updates',
	  :via => [:get],
	  :as => :event_remote_media_updates

  match '/mediastream' => 'events#featured_remote_media',
	  :via => [:get],
	  :as => :featured_media

  match '/schedule' => 'events#featured_schedule',
	  :via => [:get],
	  :as => :featured_schedule

  match '/attendees' => 'events#featured_attendees',
	  :via => [:get],
	  :as => :featured_attendees

  resources :events do
	  resources :event_attendees, :path => :attendees, :as => :attendees, :controller => :event_attendees do
		  collection do
			  match '/register' => 'event_attendees#register'
			  match '/unregister' => 'event_attendees#unregister'
		  end
	  end
	  resources :rooms
	  resources :slots
	  resources :workshops do 
		  resources :workshop_attendees, :path => :attendees, :as => :attendees, :controller => :workshop_attendees do
			  collection do
				  match '/register' => 'workshop_attendees#register'
				  match '/unregister' => 'workshop_attendees#unregister'
			  end
		  end

		  match '/sync' => 'workshops#sync',
			  :via => [:get],
			  :as => :sync
	  end
	  resources :remote_media
	  resources :sponsors
  end

  resources :users
  resources :authentications

  devise_for :users, :path => 'access'

  match '/auth/:provider/callback' => 'authentications#create'  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'events#featured'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, 
	  :admin, :avatar, :firstname, :lastname
  # attr_accessible :title, :body
  
  has_many :authentications

  has_many :event_attendees, :dependent => :destroy
  has_many :events, :through => :event_attendees

  has_many :workshop_attendees, :dependent => :destroy
  has_many :workshops, :through => :workshop_attendees


  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_attached_file :avatar, :styles => { 
	  :big => '600x600>', 
	  :medium => "300x300>", 
	  :thumb => "100x100#", 
	  :small => "48x48#" 
  }

  def name
	  self.email
  end

  def attends_to? event
	  self.events.where('event_id = ?',event.id).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# FIXME: fix signin/signup forms
	before_filter :authenticate_user!, :except => [:show]
	
	# GET /users
	# GET /users.json
	def index
		@users = User.all
	end


	# GET /users/1
	# GET /users/1.json
	def show
		@user = User.find(params[:id])
	end

	# GET /users/new
	# GET /users/new.json
	def new
		@user = User.new
	end

	# GET /users/1/edit
	def edit
		@user = User.find(params[:id])
	end

	# POST /users
	# POST /users.json
	def create
		if params[:user][:nopassword] then
			random_string =	(0...8).map{65.+(rand(25)).chr}.join
			params[:user][:password] = random_string
			params[:user][:password_confirmation] = random_string
			params[:user].delete(:nopassword)
		end
		@user = User.new(params[:user])

		if @user.save
			redirect_to @user, notice: 'User was successfully created.'
		else
			render action: "new"
		end
	end

	# PUT /users/1
	# PUT /users/1.json
	def update
		@user = User.find(params[:id])

		if params[:user][:password].blank? 
			params[:user].delete(:password) 
			params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank? 
		end 
		params[:user].delete(:current_password) 
		STDERR.puts params.inspect

		if @user.update_attributes(params[:user])
			redirect_to @user, notice: 'User was successfully updated.'
		else
			render action: "edit"
		end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_url
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_card.html.haml
.span2.attendee
	= link_to user_path(attendee.user) do
		.avatar= image_tag avatar_url(attendee.user,:medium)
	.name
		= link_to user_path(attendee.user) do
			%span.firstname
				= attendee.user.firstname
			%span.lastname
				= attendee.user.lastname
	.company
		= attendee.user.company
	.comment
		= attendee.comment
	- if content_for? :user_card_actions then
		= yield :user_card_actions

app/views/users/_form.html.haml
= form_for(@user, :html => {:class => "form-horizontal"}) do |f|
	- if @user.errors.any?
		#error_explanation
			%h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
			%ul
				- @user.errors.full_messages.each do |msg|
					%li= msg

	.control-group
		= f.label :firstname, :class => 'control-label'
		.controls
			= f.text_field :firstname, :class=>"input-xxlarge", :placeholder => "ex: John"

	.control-group
		= f.label :lastname, :class => 'control-label'
		.controls
			= f.text_field :lastname, :class=>"input-xxlarge", :placeholder => "ex: Smith"

	.control-group
		= f.label :email, :class=>"control-label"
		.controls
			= f.text_field :email, :class=>"input-xxlarge", :placeholder => "ex: john.smith@example.com"
	
	- if @user.id then
		.control-group
			= f.label :password, :class=>'control-label'
			.controls
				= f.password_field :password, :autocomplete => "off"
				.help-inline (leave blank if you don't want to change it)

		.control-group
			= f.label :password_confirmation, :class=>'control-label'
			.controls
				= f.password_field :password_confirmation

		.control-group
			= f.label :current_password, :class=>'control-label'
			.controls
				= f.password_field :current_password, :autocomplete => "off"
	- else
		= f.hidden_field :nopassword, value: "nopassword"

	.control-group
		= f.label :avatar, :class => 'control-label'
		.controls
			= f.file_field :avatar

	.control-group
		= f.label :admin, :class=>"control-label"
		.controls
			= f.check_box :admin

	.control-group
		.controls
			= f.submit 'Save', :class=>"btn btn-primary"
			= link_to 'Cancel', users_path, :class=>'btn'

app/views/users/create.html.haml
%h1 User#create
%p Find me in app/views/user/create.html.haml

app/views/users/destroy.html.haml
%h1 User#destroy
%p Find me in app/views/user/destroy.html.haml

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

app/views/users/index.html.haml
%h1 Listing users

%table
	%tr
		%th Avatar
		%th Email
		%th 

	- @users.each do |user|
		%tr
			%td
				= image_tag avatar_url(user,:small)
			%td
				= link_to user.email, user
			%td
				.btn-group.pull-right
					= link_to '', edit_user_path(user), :class=>"btn btn-small icon-edit"
					= link_to '', user, method: :delete, :class => "btn btn-small icon-remove", data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path, :class=>"btn"

app/views/users/new.html.haml
%h1= @user.email
%h2 New user

= render 'form'

/FIXME: re-enable = link_to 'Back', user_path(@user)

app/views/users/show.html.haml
- if current_user && current_user.admin? then
	.btn-group.pull-right
		=link_to edit_user_path(@user), :class => 'btn' do
			%i.icon-edit
			Edit user


%h1
	= @user.firstname 
	= @user.lastname 

.avatar
	= image_tag avatar_url(@user,:medium)

%h2 Attending on
%ul
	- @user.events.each do |event|
		%li
			= link_to event.title, event_path(event)
			- workshops = @user.workshops.where('event_id = ?',event)
			- if workshops.empty? || workshops.size < 1 then
			- else
				(workshops : 
				- workshops.map do |workshop|
					= link_to workshop.title, event_workshop_path(event,workshop)
				- .join(',')
				)

app/views/users/update.html.haml
%h1 User#update
%p Find me in app/views/user/update.html.haml