config/routes.rb
BarcampGarden::Application.routes.draw do

  match '/events/featured_schedule' => 'events#featured_schedule', 
	  :via => [:get],
	  :as => :featured_schedule

  match '/events/:id/schedule' => 'events#schedule', 
	  :via => [:get],
	  :as => :event_schedule

  match '/events/featured_missing' => 'events#featured_missing', 
	  :via => [:get],
	  :as => :featured_missing

  match '/events/:event_id/remote_media_updates(.:format)' => 'remote_media#updates',
	  :via => [:get],
	  :as => :event_remote_media_updates

  match '/mediastream' => 'events#featured_remote_media',
	  :via => [:get],
	  :as => :featured_media

  match '/schedule' => 'events#featured_schedule',
	  :via => [:get],
	  :as => :featured_schedule

  match '/attendees' => 'events#featured_attendees',
	  :via => [:get],
	  :as => :featured_attendees

  resources :events do
	  resources :event_attendees, :path => :attendees, :as => :attendees, :controller => :event_attendees do
		  collection do
			  match '/register' => 'event_attendees#register'
			  match '/unregister' => 'event_attendees#unregister'
		  end
	  end
	  resources :rooms
	  resources :slots
	  resources :workshops do 
		  resources :workshop_attendees, :path => :attendees, :as => :attendees, :controller => :workshop_attendees do
			  collection do
				  match '/register' => 'workshop_attendees#register'
				  match '/unregister' => 'workshop_attendees#unregister'
			  end
		  end

		  match '/sync' => 'workshops#sync',
			  :via => [:get],
			  :as => :sync
	  end
	  resources :remote_media
	  resources :sponsors
  end

  resources :users
  resources :authentications

  devise_for :users, :path => 'access'

  match '/auth/:provider/callback' => 'authentications#create'  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'events#featured'

end

app/models/workshop_attendee.rb
class WorkshopAttendee < ActiveRecord::Base
  attr_accessible :comment, :user, :workshop, :user_id

  belongs_to :workshop
  belongs_to :user

  validates_uniqueness_of :user_id, :scope => [:workshop_id]
end

app/controllers/workshop_attendees_controller.rb
class WorkshopAttendeesController < ApplicationController
	before_filter :find_event_workshop #, :only => [:show, :edit, :update, :destroy]
	before_filter :find_unattendees

	# GET /attendees
	# GET /attendees.json
	def index
		@attendees = @workshop.attendees.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @attendees }
		end
	end

	# GET /attendees/1
	# GET /attendees/1.json
	def show
		@attendee = @workshop.attendees.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @attendee }
		end
	end

	# GET /attendees/new
	# GET /attendees/new.json
	def new
		@attendee = @workshop.attendees.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @attendee }
		end
	end

	# GET /attendees/1/edit
	def edit
		@attendee = @workshop.attendees.find(params[:id])
	end

	# POST /attendees
	# POST /attendees.json
	def create
		@attendee = @workshop.attendees.new(params[:attendee])

		respond_to do |format|
			if @attendee.save
				format.html { redirect_to event_workshop_path(@event,@workshop), notice: 'Workshop attendee was successfully created.' }
				format.json { render json: @attendee, status: :created, location: @attendee }
			else
				format.html { render action: "new" }
				format.json { render json: @attendee.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /attendees/1
	# PUT /attendees/1.json
	def update
		@attendee = @workshop.attendees.find(params[:id])

		respond_to do |format|
			if @attendee.update_attributes(params[:attendee])
				format.html { redirect_to @attendee, notice: 'Workshop attendee was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @attendee.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /attendees/1
	# DELETE /attendees/1.json
	def destroy
		@attendee = @workshop.attendees.find(params[:id])
		@attendee.destroy

		respond_to do |format|
			format.html { redirect_to event_workshop_url(@event,@workshop) }
			format.json { head :no_content }
		end
	end

	protected
	def find_event_workshop
		@event = Event.find(params[:event_id])
		@workshop = @event.workshops.find(params[:workshop_id])
	end

	def find_unattendees
		STDERR.puts "Already attending :",
			 @workshop.attendees.all

		@users_not_attending= 
			if @workshop.attendees.empty? || @workshop.attendees.size < 1
				@event.attendees.all.map { |attendee| attendee.user }
			else
				@event.attendees.where(
					"user_id not in (?)", 
					@workshop.attendees.map{ |attendee| attendee.user_id }
				).map{ |attendee| 
					attendee.user 
				}
			end
	end
end

app/helpers/workshop_attendees_helper.rb
module WorkshopAttendeesHelper
end

app/views/workshop_attendees/_card.html.haml
- single_content_for :user_card_actions, flush: true do
	- if current_user && current_user.admin?
		.actions
			.btn_group.pull-right
				= link_to event_workshop_attendee_path(@event,@workshop,attendee), method: :delete, data: { confirm: 'Are you sure?' }, :class=> 'btn' do
					%i.icon-remove
					Remove

= render :partial => 'users/card', :locals => { :attendee => attendee }

app/views/workshop_attendees/_form.html.haml
= form_for([@event,@workshop,@attendee], :url => {:controller => 'workshop_attendees', :action=>:create },
	:html => {:class => "form-horizontal"}) do |f|
	- if @attendee.errors.any?
		#error_explanation
			%h2= "#{pluralize(@attendee.errors.count, "error")} prohibited this workshop_attendee from being saved:"
			%ul
				- @attendee.errors.full_messages.each do |msg|
					%li= msg

	.control-group
		= f.label :user, :class => 'control-label' do
			Email
		.controls
			= select :attendee, :user_id, @users_not_attending.map{ |user| [user.name, user.id] }, {:include_blank => true}

	.control-group
		.controls
			= f.submit 'Save', :class=>'btn btn-primary'

app/views/workshop_attendees/edit.html.haml
%h1 Editing workshop_attendee

= render 'form'

= link_to 'Show', @workshop_attendee
\|
= link_to 'Back', workshop_attendees_path

app/views/workshop_attendees/index.html.haml
%h1 Listing attendees

%table
  %tr
    %th Comment
    %th User
    %th Workshop
    %th
    %th
    %th

  - @attendees.each do |attendee|
    %tr
      %td= attendee.comment
      %td= attendee.user.name
      %td= attendee.workshop.title
      %td= link_to 'Destroy', event_workshop_attendee_path(@event,@workshop,attendee), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Workshop attendee', new_event_workshop_attendee_path(@event,@workshop)

app/views/workshop_attendees/new.html.haml
- title = "%s / %s : New attendee" % [@event.title, @workshop.title]
- content_for :title do
	= title

%h1= yield :title

= render 'form'

= link_to 'Back', event_workshop_attendees_path(@event,@workshop)

app/views/workshop_attendees/show.html.haml
%p#notice= notice

%p
  %b Comment:
  = @workshop_attendee.comment
%p
  %b User:
  = @workshop_attendee.user
%p
  %b Workshop:
  = @workshop_attendee.workshop

= link_to 'Edit', edit_workshop_attendee_path(@workshop_attendee)
\|
= link_to 'Back', workshop_attendees_path